# MYSQL
development:
  adapter: mysql
  database: enginey_development
  username: root
  password: r00by 
  host: localhost

test:
  adapter: mysql
  database: enginey_test
  username: root
  password: r00by 
  host: localhost
  

